version: :'3.9'

services:
  #MongoDB
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGO_INITDB_DATABASE=Corridas
      - MONGODB_APPLICATION_DATABASE=Corridas      
    restart: always
    volumes:
      - mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      

  #nodejs
  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGO_DOMINIO: mongo_db
      DB_NAME: Corridas
      DB_USER: dev
      DB_PASS: dev
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}